# Generated by Django 5.2.6 on 2025-10-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="optical",
            name="latitud",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="optical",
            name="longitud",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="optical",
            name="view",
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
