# Generated by Django 5.2.6 on 2025-10-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_user_user_permissions_alter_user_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hour",
            name="hour",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
