# Generated by Django 5.2.6 on 2025-10-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_optical_schedule_schedule_optical_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="descriptionOp",
            field=models.CharField(default="Sin descripción", max_length=500),
        ),
    ]
