# Generated by Django 5.2.5 on 2025-10-20 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_test_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=3, on_delete=django.db.models.deletion.CASCADE, to="api.role"
            ),
        ),
    ]
