# Generated by Django 5.2.7 on 2025-10-21 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_user_role"),
        ("api", "0025_optical_descriptionop"),
    ]

    operations = []
