# Generated by Django 5.2.7 on 2025-10-21 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_merge_0022_alter_user_role_0025_optical_descriptionop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optical",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="optical/logos/"),
        ),
        migrations.AlterField(
            model_name="question",
            name="image_question",
            field=models.ImageField(
                blank=True, null=True, upload_to="questionary/questions/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.role"
            ),
        ),
    ]
