# Generated by Django 5.2.6 on 2025-10-24 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id_product", models.AutoField(primary_key=True, serialize=False)),
                ("nameProduct", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "product",
                "managed": True,
            },
        ),
        migrations.AlterField(
            model_name="catalogue",
            name="nameP",
            field=models.ForeignKey(
                db_column="id_product",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.product",
            ),
        ),
    ]
